### ISSUE TITLE
Resonant Cavity Example Fails

### ISSUE THREAD

**Issue by braamotto** [cemagg/sucem-fem#8]
On clean install tried to run driver.py in the resonant cavity example.

Output:
braam@braam-laptop:~/Work_Related/CEMAGG/sucem-fem/examples/resonant_cavity$ python driver.py 
Calling FFC just-in-time (JIT) compiler, this may take some time.
File "driver.py", line 48, in <module>
    ep.set_boundary_conditions(pec=True)
TypeError: set_boundary_conditions() got an unexpected keyword argument 'pec'

**Comment by elezar** [comment]
I have committed the fix for this problem.

**Comment by elezar** [comment]
The Albani-Bernardi '74 example had the same issue. Fixed in pull Issue #10
